language: python

env:
  global:
    - REPO="johnjiang/pyconcordion2"
    - CI_HOME=`pwd`/$REPO
    - PYTHONPATH="$CI_HOME/pyconcordion2:$PYTHONPATH"

python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"
# command to run tests
script: nosetests